export default {
    PAGE_MAIN: 'PAGE_MAIN',
    PAGE_DETAIL: 'PAGE_DETAIL',
    SEARCH_INPUT_CHANGE: 'SEARCH_INPUT_CHANGE',
    SET_USERS_LIST: 'SET_USERS_LIST',
    ADD_TO_USERS_LIST: 'ADD_TO_USERS_LIST',
    EMPTY_USERS_LIST: 'EMPTY_USERS_LIST',
    SET_LIST_PAGE: 'SET_LIST_PAGE',
    CHANGE_PAGE: 'CHANGE_PAGE',
}